### ISSUE TITLE
有关预测结果的后处理请教

### ISSUE THREAD

**Issue by NY1006CR** [edgarshang/qt-model-deploy#1]
很困惑，我通过onnx拿到的预测结果为（1,3,512,512），在python端我是用numpy.argmax(output, axis=2)进行降维到（1,512,512），然后再numpy.squeeze(output)将结果转化为（512,512）就可以以图片的形式展现出来，但是在C++端没有numpy库，请问要怎样才能实现这些后处理呢？

**Comment by edgarshang** [comment]
> 很困惑，我通过onnx拿到的预测结果为（1,3,512,512），在python端我是用numpy.argmax(output, axis=2)进行降维到（1,512,512），然后再numpy.squeeze(output)将结果转化为（512,512）就可以以图片的形式展现出来，但是在C++端没有numpy库，请问要怎样才能实现这些后处理呢？

利用opencv的Mat类来转换

**Comment by NY1006CR** [comment]
cv::Mat mat_img(512, 512, CV_32F);
        for (int i = 0; i < 512; i++) {
            for (int j = 0; j < 512 ; j++) {
            float max_index = std::max({output_data[512*512 + i*mat_image.cols + j], output_data[2*512*512 + i*mat_image.cols + j]});
                mat_img.at<float>(i, j) = max_index;
        }
    }
你好，我用上述代码将其转化为cv::Mat，但是这个Mat显示出来的结果并不对，结果是这样的效果，请问是哪一步出问题了呢
![123](https://github.com/edgarshang/qt-model-deploy/assets/40394910/3fe69ddc-5541-4e47-b600-ae65cf09786b)

**Comment by NY1006CR** [comment]
> 
 for (int i = 0; i < 512; i++) {
            for (int j = 0; j < 512 ; j++) {
            float max_index = std::max({output_data[512x512 + ix512 + j], output_data[2x512x512 + ix512 + j]});
                mat_image.at<float>(i, j) = max_index;
        }
    }

你好，我用上述代码将其转化为cv::Mat，但是这个Mat显示出来的结果并不对，结果是这样的效果，请问是哪一步出问题了呢
![123](https://github.com/edgarshang/qt-model-deploy/assets/40394910/6cb6c5fb-11e4-4116-ac11-6ec6c13e9a11)

**Comment by edgarshang** [comment]
> > 
> 
> for (int i = 0; i < 512; i++) { for (int j = 0; j < 512 ; j++) { float max_index = std::max({output_data[512x512 + ix512 + j], output_data[2x512x512 + ix512 + j]}); mat_image.at(i, j) = max_index; } }
> 
> 你好，我用上述代码将其转化为cv::Mat，但是这个Mat显示出来的结果并不对，结果是这样的效果，请问是哪一步出问题了呢 ![123](https://user-images.githubusercontent.com/40394910/266842882-6cb6c5fb-11e4-4116-ac11-6ec6c13e9a11.jpg)

你这是三个通道，的图像结果然后要转为单通道？为什么要取max的呢？

**Comment by NY1006CR** [comment]
> 
是的，预测结果是三通道图像，每个通道分别代表前景、特征一、特征二的值。
想取max是因为类似于python的numpy库中的argmax函数，进行降维，将三个通道的信息集中在一张图上，C++我不是很熟，之前是用python做的后处理，对于这样的结果很困扰。。。

**Comment by NY1006CR** [comment]
> > 
> 
> 是的，预测结果是三通道图像，每个通道分别代表前景、特征一、特征二的值。 想取max是因为类似于python的numpy库中的argmax函数，进行降维，将三个通道的信息集中在一张图上，C++我不是很熟，之前是用python做的后处理，对于这样的结果很困扰。。。

说错了应该是背景、特征一、特征二的值。

**Comment by edgarshang** [comment]
`
cv::Mat result = cv::Mat::zeros(cv::Size(512, 512), CV_8UC1);
for(int i = 0; i < 512; i++)
{
     for(int j = 0; j < 512; i++)
     {
              float backGroud = output_data[i*512 + j];
              float feature1 = output_data[512*512 + i*512 + j];
              float feature2 = output_data[2*512*512 + i*512 + j];
             if (feature1 > feature2 ) 
            {
                result.at<uchar>(row, col) = 0;
             }else
            {
                result.at<uchar>(row, col) = 255;
            }
     }
}`

你是这个意思？取特征值大的那个？类似与语义分割？

**Comment by edgarshang** [comment]
> > > 
> > 
> > 
> > 是的，预测结果是三通道图像，每个通道分别代表前景、特征一、特征二的值。 想取max是因为类似于python的numpy库中的argmax函数，进行降维，将三个通道的信息集中在一张图上，C++我不是很熟，之前是用python做的后处理，对于这样的结果很困扰。。。
> 
> 说错了应该是背景、特征一、特征二的值。


> ` cv::Mat result = cv::Mat::zeros(cv::Size(512, 512), CV_8UC1); for(int i = 0; i < 512; i++) { for(int j = 0; j < 512; i++) { float backGroud = output_data[i*512 + j]; float feature1 = output_data[512*512 + i*512 + j]; float feature2 = output_data[2*512*512 + i*512 + j]; if (feature1 > feature2 ) { result.at<uchar>(row, col) = 0; }else { result.at<uchar>(row, col) = 255; } } }`
> 
> 你是这个意思？取特征值大的那个？类似与语义分割？

 cv::Mat result = cv::Mat::zeros(cv::Size(512, 512), CV_8UC1); for(int i = 0; i < 512; i++) { for(int j = 0; j < 512; i++) { float backGroud = output_data[i*512 + j]; float feature1 = output_data[512*512 + i*512 + j]; float feature2 = output_data[2*512*512 + i*512 + j]; if (feature1 > feature2 )  { result.at<uchar>(row, col) = 0; }else { result.at<uchar>(row, col) = 255; } } }

你是这个意思？取特征值大的那个？类似与语义分割？

**Comment by edgarshang** [comment]
> > > 
> > 
> > 
> > 是的，预测结果是三通道图像，每个通道分别代表前景、特征一、特征二的值。 想取max是因为类似于python的numpy库中的argmax函数，进行降维，将三个通道的信息集中在一张图上，C++我不是很熟，之前是用python做的后处理，对于这样的结果很困扰。。。
> 
> 说错了应该是背景、特征一、特征二的值。

cv::Mat result = cv::Mat::zeros(cv::Size(512, 512), CV_8UC1); for(int i = 0; i < 512; i++) { for(int j = 0; j < 512; i++) { float backGroud = output_data[i*512 + j]; float feature1 = output_data[512*512 + i*512 + j]; float feature2 = output_data[2*512*512 + i*512 + j]; if (feature1 > feature2 ) { result.at<uchar>(row, col) = 0; }else { result.at<uchar>(row, col) = 255; } } }

你是这个意思？取特征值大的那个？类似与语义分割？

**Comment by edgarshang** [comment]
> > > 
> > 
> > 
> > 是的，预测结果是三通道图像，每个通道分别代表前景、特征一、特征二的值。 想取max是因为类似于python的numpy库中的argmax函数，进行降维，将三个通道的信息集中在一张图上，C++我不是很熟，之前是用python做的后处理，对于这样的结果很困扰。。。
> 
> 说错了应该是背景、特征一、特征二的值。

![image](https://github.com/edgarshang/qt-model-deploy/assets/19580827/72501921-8d6c-46fa-82c5-d4abbc2a6023)

**Comment by NY1006CR** [comment]
是的语义分割，感谢回复，明天我去试试您的代码



------------------ 原始邮件 ------------------
发件人: FF ***@***.***&gt;
发送时间: 2023年9月10日 23:14
收件人: edgarshang/qt-model-deploy ***@***.***&gt;
抄送: Nie Yu ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [edgarshang/qt-model-deploy] 有关预测结果的后处理请教 (Issue #1)





     
是的，预测结果是三通道图像，每个通道分别代表前景、特征一、特征二的值。 想取max是因为类似于python的numpy库中的argmax函数，进行降维，将三个通道的信息集中在一张图上，C++我不是很熟，之前是用python做的后处理，对于这样的结果很困扰。。。
  
说错了应该是背景、特征一、特征二的值。

**Comment by NY1006CR** [comment]
[i*512 + j]的结果依然是这样
![3d4cce213b300759eecd3df7c7475e3](https://github.com/edgarshang/qt-model-deploy/assets/40394910/c4f6cd78-b8c3-4b17-872c-de19949942bc)
但是我将代码改成[i*512 + j/3]就得到了如下的结果
![7f840d2960ef3a06cac651b11f47182](https://github.com/edgarshang/qt-model-deploy/assets/40394910/52a0f7d3-a298-4d00-9e7c-21e23481dd91)
